@authorProfilePageControl
Feature: AuthorProfilePageControl feature

  @authorDetails1 @regression
  Scenario: MENDELEY PROFILE - Verify clicking Claim Account redirects to Mendeley profile
    Given I navigate to the details page of author with "7801469910" id
    When I click on "Is this you?" link
    Then I verify new page is displayed with "Welcome" title

  @authorDetails2 @regression
  Scenario: Support Center link - Verify the text with a link to the support centre is available
    Given I navigate to the details page of author with "7801469910" id
    Then I verify the text "This author profile is generated by Scopus" is shown in the author details card
    When I click on "Learn more" link in author general details section
    Then I verify new page is displayed with "Scopus Author Profile FAQs" title

  @authorDetails3 @regression
  Scenario: AFFILIATION LINK - Verify affiliation link on author profile goes to affiliation details page
    Given I navigate to the details page of author with "57198148688" id
    And I click on "Affiliation" link in author details
    Then I verify "Affiliation details" page is displayed

  @authorDetails4 @regression
  Scenario: AUTHOR AFFILIATION HISTORY - Verify that affiliation history is displayed for author and that full affiliation history is shown in a modal.
    Given I navigate to the details page of author with "36051235900" id
    Then I verify that "National and Kapodistrian University of Athens" is the author's affiliation
    When I click on "View more" button
    Then I verify that more items from the affiliation history are displayed

  @authorDetails5 @regression
  Scenario: CO-AUTHORS TAB - If an author has no co-authors, "no co-authors" message should not be displayed
    Given I navigate to the details page of author with "56595587800" id
    Then I click on "co-authors" tab in author profile page
    And I verify that the "co-authors" tab panel contains the text "There are no co-authors linked to this author profile."

  @authorDetails6 @regression
  Scenario: AUTHOR GENERAL INFO - Verify the information shown in the general info.
    Given I navigate to the details page of author with "7401500378" id
    Then I verify that the author name is "Brown, Herbert C."
    And I verify that the author id is "7401500378"
    When I click on "View more" button
    Then I verify that the subject "Chemistry" is among the subject areas

  @authorDetails7 @regression
  Scenario Outline: RELATED DOCUMENTS - Verify that the related documents link is displayed in document results and Cited by document tab
    Given I navigate to the details page of author with "7005680145" id
    When I click on "<tabName>" sub tab in author profile page
    And I click on "Related documents" link in the results
    Then I verify "Shares references with:" page is displayed
    And I verify "documents share references with:" is the page header

    Examples:
      | tabName   |
      | documents |
      | cited-by  |
      | preprints |

  @authorDetails8 @regression
  Scenario Outline: CITED BY COUNT - Verify that the Cited by count link is displayed in document results and Cited by documents tab
    Given I navigate to the details page of author with "57210766486" id
    When I click on "<authorDetailsTabName>" sub tab in author profile page
    And I select "Cited by (highest)" option in the results
    And I click on "Cited by count" link in the results
    Then I verify "<title>" page is displayed
    And I verify "documents have cited:" is the page header

    Examples:
      | authorDetailsTabName | title                 |
      | documents            | documents that cite:  |
      | cited-by             | documents have cited: |

  @authorDetails9 @regression
  Scenario: AUTHOR DOCUMENTS TABS - Verify that all documents sub tabs are reachable
    Given I navigate to the details page of author with "7401500378" id
    Then I verify that the author id is "7401500378"
    And I verify that "documents" sub tab is loaded
    When I click on "cited-by" sub tab in author profile page
    Then I verify that "citedBy" sub tab is loaded
    When I click on "preprints" sub tab in author profile page
    Then I verify that "preprints" sub tab is loaded

  @authorDetails10 @regression
  Scenario: AUTHOR DOCUMENTS TABS - Verify that the sub tabs can be reached via url
    Given I navigate to the details page of author with "7401500378" id and "cited-by" tab
    Then I verify that the author name is "Brown, Herbert C."
    And I verify that the author id is "7401500378"
    And I verify that "citedBy" sub tab is loaded

  @authorDetails11 @regression
  Scenario: AUTHOR DOCUMENTS TABS - Verify the document sub tab is open by default when clicking on main documents tab
    Given I navigate to the details page of author with "7401500378" id
    And I verify that the author id is "7401500378"
    When I click on "co-authors" tab in author profile page
    And I click on "documents" tab in author profile page
    Then I verify that "documents" sub tab is loaded

  @authorDetails12 @regression
  Scenario Outline: SHOW/HIDE ABSTRACT - Verify that abstract content is displayed/hidden by clicking Show/hide abstract button
    Given I navigate to the details page of author with "7005680145" id and "<tabName>" tab
    Then I verify that the abstract dropdown is "collapsed"
    And I verify that the abstract content is "hidden"
    When I click on "Show abstract" button
    Then I verify that the abstract dropdown is "expanded"
    And I verify that the abstract content is "visible"
    When I click on "Hide abstract" button
    Then I verify that the abstract dropdown is "collapsed"
    And I verify that the abstract content is "hidden"

    Examples:
      | tabName   |
      | documents |
      | cited-by  |
      | preprints |

  @authorDetails13 @regression
  Scenario Outline: SIDE MENU LINKS - Verify the Side Menu links in document results and Cited by documents tabs
    Given I navigate to the details page of author with "55723678100" id and "<tabName>" tab
    When I click on "<sideMenuLink>" link in the side menu
    Then I verify "<pageTitle>" page is displayed
    And I verify "<pageHeader>" is the page header

    Examples:
      | tabName   | sideMenuLink                       | pageTitle                                           | pageHeader            |
      | documents | View list in search results format | Document search results                             | document results      |
      | documents | View references                    | references cited by: \"Smith, Paul R.\" 55723678100 | references cited by:  |
      | cited-by  | View list in search results format | documents have cited:                               | documents have cited: |

  @authorDetails14 @regression
  Scenario Outline: DOCUMENT TITLES - Verify document title links in document results and Cited by documents tabs
    Given I navigate to the details page of author with "7005680145" id and "<tabName>" tab
    When I click on "Document title" link in the results
    Then I verify "Document details" page is displayed

    Examples:
      | tabName   |
      | documents |
      | cited-by  |
      | preprints |

  @authorDetails15 @regression
  Scenario Outline: AUTHOR NAME LINKS - Verify author name link in document results and Cited by documents tab
    Given I navigate to the details page of author with "7005680145" id and "<tabName>" tab
    When I click on "Author name" link in the results
    Then I verify "Author details" page is displayed

    Examples:
      | tabName   |
      | documents |
      | cited-by  |
      | preprints |

  @authorDetails16 @regression
  Scenario Outline: ADD TO LIST - Verify add to list functionality in document results and Cited by documents tab
    Given I navigate to the details page of author with "35354080500" id and "<tabName>" tab
    And I click on "Add all to list" button
    Then I verify that "The selected 2000 documents were added to your temporary list. View or manage your list." message is displayed

    Examples:
      | tabName   |
      | documents |
      | cited-by  |

  @authorDetails17 @regression
  Scenario Outline: CITED BY COUNT - Verify Cited By count is NOT a link for ZERO citations in results
    Given I navigate to the details page of author with "36927778600" id and "<tabName>" tab
    Then I verify Cited By count is NOT a link for ZERO citations

    Examples:
      | tabName   |
      | documents |
      | cited-by  |

  @authorDetails18 @regression
  Scenario Outline: AUTHOR NAMES - Verify author name link in document results and Cited by documents tab
    Acceptance:
    - If more than 5 authors exist, display (, ...) in between.
    Given I navigate to the details page of author with "9536425000" id and "<tabName>" tab
    And I save the api response for "<tabName>" tab
    Then I verify that max 5 author names are displayed in each results
    And I verify that last two names are seperated by three dots if more than 5 authors exist
    Examples:
      | tabName  |
      #      | documents | activate it when RTSC-51573 is resolved
      | cited-by |

  @authorDetails19 @regression
  Scenario Outline: AUTHORS AND DOCUMENTS - Verify authors and documents name in results list
    Acceptance:
    - If <=5 authors exist, show all authors in the order delivered in the response
    Given I navigate to the details page of author with "35463678800" id and "<tabName>" tab
    When I select "Date (oldest)" option in the results
    Then I verify the authors "<authorNames>" displayed with the document "<documentName>"

    Examples:
      | tabName   | documentName                                                                                                          | authorNames                   |
      | documents | Fluorescence of nitric oxide. Part 2.-Vibrational energy transfer between                                             | Callear, A.B., Smith, I.W.M.  |
      | documents | Fluorescence of nitric oxide. Part 1.-Determination of the mean lifetime of the A2Σ+ state                            | Callear, A.B., Smith, I.W.M.  |
      | cited-by  | MASS SPECTROMETRIC STUDIES OF THE REACTIONS OF SINGLET OXYGEN IN THE GAS PHASE                                        | Herron, J.T., Huie, R.E.      |
      | cited-by  | Flash spectroscopy with mercury resonance radiation. Part 1. - An experimental method with microwave-pulse excitation | Callear, A.B., Hedges, R.E.M. |


  @authorDetails20 @regression
  Scenario Outline: AUTHORS AND DOCUMENTS - Verify authors and documents name in results list
    Acceptance:
    - If <=5 authors exist, show all authors in the order delivered in the response
    Given I navigate to the details page of author with "<authorID>" id and "<tabName>" tab
    Then I select "Date (oldest)" option in the results
    And I verify the authors "<authorNames>" displayed with the document "<documentName>"

    Examples:
      | tabName   | authorID    | documentName                                                                                                          | authorNames                   |
      | documents | 35463678800 | Vibrational energy transfer between N                                                                                 | Callear, A.B., Smith, I.W.M.  |
      | documents | 35463678800 | Fluorescence of nitric oxide. Part 2.-Vibrational energy transfer between NO A                                        | Callear, A.B., Smith, I.W.M.  |
      | cited-by  | 35463678800 | MASS SPECTROMETRIC STUDIES OF THE REACTIONS OF SINGLET OXYGEN IN THE GAS PHASE                                        | Herron, J.T., Huie, R.E.      |
      | cited-by  | 35463678800 | Flash spectroscopy with mercury resonance radiation. Part 1. - An experimental method with microwave-pulse excitation | Callear, A.B., Hedges, R.E.M. |

  @authorDetails21 @regression
  Scenario Outline: ADD TO LIST & DELETE LIST (Signed User) - Verify 'add to list' and 'delete list' functionalities for <tabName> tab
    Given I navigate to Scopus home page
    And I am logged into scopus as "SCOPUS_USER"
    And I navigate to the details page of author with "7406754790" id and "<tabName>" tab
    When I click on "Save all to list" button
    And I save the list with "<listName>" name in author details page
    Then I verify that "<savedMessage>" message is displayed
    When I click on "View or manage your saved lists" link in author details page
    Then I verify "Saved lists" page is displayed
    When I delete "<listName>" the list in list overview page
    Then I verify that "<deleteMessage>" message is displayed

    Examples:
      | tabName   | listName       | savedMessage                           | deleteMessage                                    |
      | documents | documents-list | documents were added to documents-list | \"documents-list\" has been successfully removed |
      | cited-by  | cited-by-list  | documents were added to cited-by-list  | \"cited-by-list\" has been successfully removed  |

  @authorDetails22 @regression
  Scenario Outline: PREPRINTS & AWARDED GRANTS - Verify notification title and description for <tabName> tab
    Given I navigate to the details page of author with "<authorID>" id and "<tabName>" tab
    Then I verify that the notification title of "<tabName>" tab is "<title>"
    And I verify that the notification text of "<tabName>" tab is "<notificationText>"

    Examples:
      | tabName   | authorID    | title                                              | notificationText                                                                                                                                                                                                                                                                                                                                                                              |
      | preprints | 56411591100 | New in Scopus: Preprints                           | We have added preprints to author profiles to help you discover the latest contributions of a researcher. Preprints are non-peer reviewed publications and are directly derived from arXiv, bioRxiv, ChemRxiv, medRxiv SSRN, TechRxiv and Research Square servers and follow their respective curation policies. Preprints do not affect existing publication and citation metrics in Scopus. |
      #Awarded grants with >0 grants
      | grants    | 6701628102  | New feature: Awarded grants                        | We now show funding awards associated with this profile from a selection of key global funders. We continue to expand our coverage to include more funders. Learn more\nOpens in a new tab                                                                                                                                                                                                    |
      #Awarded Grants with 0 grants
      | grants    | 56411591100 | There are no Awarded grants linked to this profile | We now show funding awards associated with this profile from a selection of key global funders. We continue to expand our coverage to include more funders. Learn more\nOpens in a new tab                                                                                                                                                                                                    |

  @authorDetails23 @regression
  Scenario: ZERO PREPRINTS - Verify empty results message when author doesn't have preprints
    Given I navigate to the details page of author with "35463678800" id and "preprints" tab
    Then I verify that "There are no preprints linked to this author profile." is displayed for empty results

  @authorDetails24 @regression
  Scenario: PREPRINTS - Verify Metrics and Cited By is not displayed and Related documents section is displayed
    when going to the document details page from preprint tab
    Given I navigate to the details page of author with "35226941100" id and "preprints" tab
    When I click on "Document title" link in the results
    Then I verify "Document details" page is displayed
    And I verify that "metrics" section is not visible on document details page
    And I verify that "citedBy" section is not visible on document details page
    And I verify that "relatedDocuments" section is visible on document details page

  @authorDetails25 @regression @test
  Scenario: AUTHOR TOOLBAR - Verify toolbar modes and elements on scroll
    Given I navigate to the details page of author with "35226941100" id
    Then I verify that the author toolbar is in "unsticky" mode
    When I scroll down to the bottom of the page
    Then I verify that the author toolbar is in "sticky" mode
    And I verify that the author toolbar has following elements:
      | Author name | Set alert | More |
    And I verify that More dropdown has following options in author toolbar:
      | Edit profile | Potential author matches | Export to SciVal |

    When I am logged into scopus as "SCOPUS_USER"
    And I scroll down to the bottom of the page
    Then I verify that the author toolbar is in "sticky" mode
    And I verify that the author toolbar has following elements:
      | Author name | Set alert | Add author to list | More |
    And I verify that More dropdown has following options in author toolbar:
      | Edit profile | Potential author matches | Export to SciVal |

    When I enable preview mode
    And I scroll down to the bottom of the page
    Then I verify that the author toolbar is in "sticky" mode
    And I verify that the author toolbar has following elements:
      | Author name | Edit profile |
